server {
    listen 80;
    # WICHTIG: Domain anpassen
    server_name tickets.deinedomain.de;

    client_max_body_size 20M;

    location /static/ {
        alias /home/ticket/ticket-system/staticfiles/;
        expires 30d;
    }

    location /media/ {
        alias /home/ticket/ticket-system/media/;
    }

    location / {
        proxy_pass http://unix:/home/ticket/ticket-system/gunicorn.sock;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
    }
}
