# Generated by Django 5.2.14 on 2026-05-07 16:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="Datum"
                    ),
                ),
                (
                    "travel_km",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Gefahrene Kilometer (einfach oder Hin+Rück, wie ihr es handhabt).",
                        max_digits=7,
                        verbose_name="Anfahrt (km)",
                    ),
                ),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Stunden, z. B. 1.5 für 1 Std 30 Min.",
                        max_digits=5,
                        verbose_name="Zeitaufwand (Std.)",
                    ),
                ),
                (
                    "material",
                    models.TextField(
                        blank=True,
                        help_text="Eingesetzte Teile/Material, z. B. '1× Netzteil 65W, 2m Patchkabel'.",
                        verbose_name="Material",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Durchgeführte Arbeiten"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="worklogs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bearbeiter",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worklogs",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aufwand",
                "verbose_name_plural": "Aufwände",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
